import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import SideButton from "@/components/SideButton";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <SideButton />
      </body>
    </html>
  );
}
